version: "3"
services:
  channel-watch:
    container_name: channel-watch
    network_mode: bridge
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 57501:3000